name: $(date:yyyyMMdd)$(rev:.rr) #20200319.00

pr:
  - master

stages:
  - stage: build
    jobs:
      - job: build_dotnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build
            # workingDirectory: ./p1_project

  - stage: analyze

  - stage: test
    jobs:
      - job: test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test --collect:"XPlat Code Coverage"
            #workingDirectory: ./p1_project

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              docker login
              docker image build -f dockerfile -t andrewagatep/p1proj .
              docker image push andrewagatep/p1proj
              docker logout
            #workingDirectory: ./p1_project

  
trigger:
  - master

variables: