// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPizza.Storage.Database;

namespace MyPizza.Storage.Migrations
{
    [DbContext(typeof(MyPizzaDbContext))]
    partial class MyPizzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyPizza.Domain.Models.Crust", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PizzaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("Crust");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Cheese Stuffed"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Thin Crust"
                        });
                });

            modelBuilder.Entity("MyPizza.Domain.Models.Pizza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Crustid")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long>("Sizeid")
                        .HasColumnType("bigint");

                    b.Property<long>("Storeid")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Crustid = 1L,
                            Name = "Cheese Pizza",
                            Price = 5.0,
                            Sizeid = 1L,
                            Storeid = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Crustid = 2L,
                            Name = "Pepperoni Pizza",
                            Price = 6.5,
                            Sizeid = 2L,
                            Storeid = 1L
                        });
                });

            modelBuilder.Entity("MyPizza.Domain.Models.Size", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PizzaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Large"
                        });
                });

            modelBuilder.Entity("MyPizza.Domain.Models.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Domino's"
                        });
                });

            modelBuilder.Entity("MyPizza.Domain.Models.Topping", b =>
                {
                    b.Property<long>("Toppingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Toppingid");

                    b.ToTable("Topping");
                });

            modelBuilder.Entity("MyPizza.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Domino's"
                        });
                });

            modelBuilder.Entity("MyPizza.Domain.Models.Crust", b =>
                {
                    b.HasOne("MyPizza.Domain.Models.Pizza", "Pizza")
                        .WithMany("Crusts")
                        .HasForeignKey("PizzaId");
                });

            modelBuilder.Entity("MyPizza.Domain.Models.Size", b =>
                {
                    b.HasOne("MyPizza.Domain.Models.Pizza", "Pizza")
                        .WithMany("Sizes")
                        .HasForeignKey("PizzaId");
                });
#pragma warning restore 612, 618
        }
    }
}
